baseURL = 'https://rdququ.top/'
languageCode = 'en-us'
title = "rdququ's Blog"
theme = "hugo-book"

disqusShortname = "rdququ's Blog"
enableGitInfo = true

[params]
  BookComments = true
  BookTheme = "light"
  BookToC = true
  BookSearch = true
  BookPortableLinks = true


[caches]
  [caches.images]
    dir = ':cacheDir/images'